### ISSUE TITLE
crash on a summary

### ISSUE THREAD

**Issue by mr-aau** [franciscoBSalgueiro/en-croissant#125]
### Describe the bug

If one of engines is broken (cloud timeout) running summary end with stack trace threw in your face.
Notification by gray box or sth, and just continue to display other engines sounds more reasonable

### Reproduction

1.go to board
2. open analysis board
3. open "analysis "card
4. click "Run >>" (I got lichess cloud, chess db, stockfish) when one of engines don't respond (issues with chess db in my case)

### Platform and versions

windows 10, N/A I believe 

### Stack trace

```Shell
Cannot read properties of undefined (reading 'score')
TypeError: Cannot read properties of undefined (reading 'score')
    at Object.read (https://tauri.localhost/assets/index.js:275:2549)
    at h (https://tauri.localhost/assets/index.js:274:2880)
    at https://tauri.localhost/assets/index.js:274:3463
    at Set.forEach (<anonymous>)
    at R (https://tauri.localhost/assets/index.js:274:3339)
    at b (https://tauri.localhost/assets/index.js:274:3521)
    at R (https://tauri.localhost/assets/index.js:274:3686)
    at r.write (https://tauri.localhost/assets/index.js:274:219)
    at E (https://tauri.localhost/assets/index.js:274:3830)
    at Object.w [as set] (https://tauri.localhost/assets/index.js:274:3882)
```

**Comment by franciscoBSalgueiro** [comment]
I believe this was already fixed by https://github.com/franciscoBSalgueiro/en-croissant/commit/ec5a3f02135b38821dd764d047bddd331d28e215. It should be fixed in the next release, or if you want you can build from source.
