### ISSUE TITLE
exception after game report generation

### ISSUE THREAD

**Issue by q6276270** [franciscoBSalgueiro/en-croissant#174]
### Describe the bug

exception

### Reproduction

1. Load a game via open file
2. download stockfish
3. try to generate report in stockfish with some depth (i picked 15)
4. at the end of the report generation it crashes.

### Platform and versions

windows 10, latest en croissant

### Stack trace

```Shell
Cannot read properties of undefined (reading 'score')
TypeError: Cannot read properties of undefined (reading 'score')
    at Y5e (https://tauri.localhost/assets/index.js:143:4643)
    at https://tauri.localhost/assets/index.js:143:2165
    at fg.with (https://tauri.localhost/assets/index.js:43:8118)
    at bJ (https://tauri.localhost/assets/index.js:143:2115)
    at https://tauri.localhost/assets/index.js:243:900385
    at wIe.produce (https://tauri.localhost/assets/index.js:243:900536)
    at https://tauri.localhost/assets/index.js:243:900370
    at Object.ax [as useReducer] (https://tauri.localhost/assets/index.js:38:20835)
    at Nt.useReducer (https://tauri.localhost/assets/index.js:9:6300)
    at Xre (https://tauri.localhost/assets/index.js:243:902397)
```

**Comment by franciscoBSalgueiro** [comment]
This has already been fixed. You can use the [pre-release](https://github.com/franciscoBSalgueiro/en-croissant/releases/tag/master-beta) version or wait for the next patch.
