### ISSUE TITLE
Cannot analyze imported game

### ISSUE THREAD

**Issue by hiIExistMan** [franciscoBSalgueiro/en-croissant#179]
### Describe the bug

I am trying to analyze my game, but it throws the following error:

Cannot read properties of undefined (reading 'score')
TypeError: Cannot read properties of undefined (reading 'score')
    at Y5e (https://tauri.localhost/assets/index.js:143:4643)
    at https://tauri.localhost/assets/index.js:143:2165
    at fg.with (https://tauri.localhost/assets/index.js:43:8118)
    at bJ (https://tauri.localhost/assets/index.js:143:2115)
    at https://tauri.localhost/assets/index.js:243:900385
    at wIe.produce (https://tauri.localhost/assets/index.js:243:900536)
    at https://tauri.localhost/assets/index.js:243:900370
    at Object.ax [as useReducer] (https://tauri.localhost/assets/index.js:38:20835)
    at Nt.useReducer (https://tauri.localhost/assets/index.js:9:6300)
    at Xre (https://tauri.localhost/assets/index.js:243:902397)

I have pasted the pgn into a default analysis window, and that didn't work either, but playing the moves out manually on the board does fix it and allow me to analyze the game

### Reproduction

1. Open game via database
2. Go to analysis >> report menu
3. Run report with stockfish

### Platform and versions

Windows 10
En Croissant 0.9.1
stockfish 16

### Stack trace

```Shell
Cannot read properties of undefined (reading 'score')
TypeError: Cannot read properties of undefined (reading 'score')
    at Y5e (https://tauri.localhost/assets/index.js:143:4643)
    at https://tauri.localhost/assets/index.js:143:2165
    at fg.with (https://tauri.localhost/assets/index.js:43:8118)
    at bJ (https://tauri.localhost/assets/index.js:143:2115)
    at https://tauri.localhost/assets/index.js:243:900385
    at wIe.produce (https://tauri.localhost/assets/index.js:243:900536)
    at https://tauri.localhost/assets/index.js:243:900370
    at Object.ax [as useReducer] (https://tauri.localhost/assets/index.js:38:20835)
    at Nt.useReducer (https://tauri.localhost/assets/index.js:9:6300)
    at Xre (https://tauri.localhost/assets/index.js:243:902397)
```

**Comment by franciscoBSalgueiro** [comment]
This has already been fixed. You can use the [pre-release](https://github.com/franciscoBSalgueiro/en-croissant/releases/tag/master-beta) version or wait for the next patch.
