### ISSUE TITLE
Error when removing an engine 

### ISSUE THREAD

**Issue by Count-MHM** [franciscoBSalgueiro/en-croissant#264]
### Describe the bug

![2024-04-03 20_55_30-](https://github.com/franciscoBSalgueiro/en-croissant/assets/71083058/513b2325-a516-41d8-9081-b2d1c2611272)

### Reproduction

1. add a chess engine with any method
2. remove a chess engine
3. ERROR

### Platform and versions

Windows 11 22631.3296
En-Croissant 0.10.0

### Stack trace

```Shell
Cannot read properties of undefined (reading 'type')
TypeError: Cannot read properties of undefined (reading 'type')
    at Hrt (https://tauri.localhost/assets/index.js:260:36759)
    at PI (https://tauri.localhost/assets/index.js:38:19576)
    at MO (https://tauri.localhost/assets/index.js:40:3150)
    at boe (https://tauri.localhost/assets/index.js:40:44967)
    at goe (https://tauri.localhost/assets/index.js:40:39894)
    at W9e (https://tauri.localhost/assets/index.js:40:39817)
    at Cy (https://tauri.localhost/assets/index.js:40:39666)
    at $O (https://tauri.localhost/assets/index.js:40:36022)
    at aW (https://tauri.localhost/assets/index.js:40:36827)
    at Z1 (https://tauri.localhost/assets/index.js:38:3292)
```

**Comment by franciscoBSalgueiro** [comment]
thanks, it was fixed
