### ISSUE TITLE
En Croissant crashes around game end

### ISSUE THREAD

**Issue by JimViebke** [franciscoBSalgueiro/en-croissant#344]
### Describe the bug

While playing my engine against Stockfish, En Croissant crashes at around the time the last couple of moves are played.

From my engine's logs, it looks like En Croissant stopped sending position commands:

```
17:44:02.6497073 Got command: position fen rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1 moves d2d4 d7d5 c2c4 d5c4 e2e4 e7e5 g1f3 e5d4 f1c4 b8c6 e1g1 g8f6 d1b3 d8e7 b1a3 f6e4 f1e1 f7f5 c1g5 e7d7 a3b5 f8e7 c4e6 d7d8 e6g8 e4g5 f3g5 h8g8 b3f7 e8d7 f7f5 d7e8 f5f7 e8d7 f7d5 d7e8 d5g8 e8d7 g8e6 d7e8 e6f7 e8d7 a1d1 d8f8 f7d5 e7d6 d5e6 d7d8 g5f7 f8f7 e6f7 d6h2 g1h2 c8d7 f7g8
17:44:02.6514103 Got command: go wtime 26100 btime 30100 winc 1000 binc 1000
17:44:02.6530565 Sending UCI command: info pv d7e8
17:44:02.6532587 Sending UCI command: bestmove d7e8
17:44:13.7223363 Got command: stop
17:44:13.7742626 Got command: go wtime 27100 btime 19000 winc 1000 binc 1000
17:44:13.7764499 Sending UCI command: info depth 1 score cp 1379 nps 3000 nodes 3 hashfull 864 tbhits 1 time 0 pv g8e8
17:44:13.7766831 Sending UCI command: info depth 1 score cp 1421 nps 5000 nodes 5 hashfull 864 tbhits 1 time 1 pv e1e8
17:44:13.7774674 Sending UCI command: info depth 2 score cp 1860 nps 11000 nodes 11 hashfull 864 tbhits 0 time 0 pv e1e8 d8d7
17:44:13.7776963 Sending UCI command: info depth 2 score mate 1 nps 12000 nodes 12 hashfull 864 tbhits 1 time 1 pv g8e8
17:44:13.7784950 Sending UCI command: info pv g8e8
17:44:13.7787120 Sending UCI command: bestmove g8e8
17:44:17.3510595 Got command: stop
17:44:17.4057671 Got command: go wtime 27100 btime 15400 winc 1000 binc 1000
17:44:19.2469122 Got command: stop
17:44:19.3020239 Got command: go wtime 27100 btime 13500 winc 1000 binc 1000
```

### Reproduction

.

### Platform and versions

Version: 0.11.0
Tauri version: 1.6.1
OS: Windows_NT x86_64 10.0.19045

### Stack trace

```Shell
Stack trace 1:

Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Ol (https://tauri.localhost/assets/index.js:40:33914)
    at Wye (https://tauri.localhost/assets/index.js:38:24954)
    at Rw (https://tauri.localhost/assets/index.js:80:15863)
    at https://tauri.localhost/assets/index.js:80:15970
    at Array.forEach (<anonymous>)
    at https://tauri.localhost/assets/index.js:80:15959
    at Rw (https://tauri.localhost/assets/index.js:80:15863)
    at https://tauri.localhost/assets/index.js:80:15970
    at Array.forEach (<anonymous>)
    at https://tauri.localhost/assets/index.js:80:15959

Stack trace 2:

Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Ol (https://tauri.localhost/assets/index.js:40:33914)
    at Wye (https://tauri.localhost/assets/index.js:38:24954)
    at Rw (https://tauri.localhost/assets/index.js:80:15863)
    at https://tauri.localhost/assets/index.js:80:15970
    at Array.forEach (<anonymous>)
    at https://tauri.localhost/assets/index.js:80:15959
    at Rw (https://tauri.localhost/assets/index.js:80:15863)
    at https://tauri.localhost/assets/index.js:80:15970
    at Array.forEach (<anonymous>)
    at https://tauri.localhost/assets/index.js:80:15959
```

**Comment by JimViebke** [comment]
This also occurs if both engines are Stockfish.
