### ISSUE TITLE
Can't use duplicated engine

### ISSUE THREAD

**Issue by OutsiderH** [franciscoBSalgueiro/en-croissant#369]
### Describe the bug

If "your engines" contains two or more engines that point to the same file, then opening any drop-down that contains an engine list will cause an error.

### Reproduction

1. import two engines that point to the same file.
2. open the drop-down.

### Platform and versions

windows 10 x86-64

### Stack trace

```Shell
[@mantine/core] Duplicate options are not supported. Option with value "D:\*****\stockfish-windows-x86-64-bmi2.exe" was provided more than once
Error: [@mantine/core] Duplicate options are not supported. Option with value "D:\*****\stockfish-windows-x86-64-bmi2.exe" was provided more than once
    at ace (https://tauri.localhost/assets/index.js:83:140304)
    at oce (https://tauri.localhost/assets/index.js:83:141464)
    at cL (https://tauri.localhost/assets/index.js:38:19576)
    at lse (https://tauri.localhost/assets/index.js:40:44191)
    at ise (https://tauri.localhost/assets/index.js:40:39894)
    at cbe (https://tauri.localhost/assets/index.js:40:39817)
    at qy (https://tauri.localhost/assets/index.js:40:39666)
    at fO (https://tauri.localhost/assets/index.js:40:36022)
    at jW (https://tauri.localhost/assets/index.js:40:36827)
    at rd (https://tauri.localhost/assets/index.js:38:3292)
```

**Comment by franciscoBSalgueiro** [comment]
Fixed by https://github.com/franciscoBSalgueiro/en-croissant/commit/73207410f0059b0e52192b0aa0b1e65147dbfe37
