### ISSUE TITLE
Time end error

### ISSUE THREAD

**Issue by abrarishere** [franciscoBSalgueiro/en-croissant#416]
### Describe the bug

When I play against engine and any of us loss on time or just any player win, then it shows error. 

### Reproduction

1. Play against engine
2. Set Engine time very low or loss on time against engine or when game ends and any player win.
3. See this error message

### Platform and versions

Windows 10
Latest exe from web

### Stack trace

```Shell
Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings. Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.     at Dl (https://tauri.localhost/assets/index.js:40:33914)     at Yye (https://tauri.localhost/assets/index.js:38:24954)     at Nw (https://tauri.localhost/assets/index.js:80:15863)     at https://tauri.localhost/assets/index.js:80:15970     at Array.forEach (<anonymous>)     at https://tauri.localhost/assets/index.js:80:15959     at Nw (https://tauri.localhost/assets/index.js:80:15863)     at https://tauri.localhost/assets/index.js:80:15970     at Array.forEach (<anonymous>)     at https://tauri.localhost/assets/index.js:80:15959
```

**Comment by Nullsp4ce** [comment]
possible duplicate #368 
#385 also has great description
