### ISSUE TITLE
Problem while saving to database

### ISSUE THREAD

**Issue by Mattikowski** [franciscoBSalgueiro/en-croissant#418]
### Describe the bug

When saving a game to a database, I receive an error message and my save fails.

### Reproduction

1. Add game on the board
2. Try to save it to an existing PGN
3. Error o
![github](https://github.com/user-attachments/assets/7b3270b9-26a9-4a80-bb81-9ea213d57756)
ccurs

### Platform and versions

En Croissant
Version: 0.11.1

Tauri version: 1.6.1

OS: Windows_NT x86_64 10.0.22631

**Comment by Mattikowski** [comment]
Stack Trace:

Minified React error #310; visit https://reactjs.org/docs/error-decoder.html?invariant=310 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
Error: Minified React error #310; visit https://reactjs.org/docs/error-decoder.html?invariant=310 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Vs (https://tauri.localhost/assets/index.js:38:20174)
    at Object.OT [as useReducer] (https://tauri.localhost/assets/index.js:38:20428)
    at Kt.useReducer (https://tauri.localhost/assets/index.js:9:6321)
    at nt (https://tauri.localhost/assets/index.js:109:13690)
    at kDn (https://tauri.localhost/assets/index.js:477:79779)
    at cL (https://tauri.localhost/assets/index.js:38:19576)
    at tO (https://tauri.localhost/assets/index.js:40:3150)
    at lse (https://tauri.localhost/assets/index.js:40:44967)
    at ise (https://tauri.localhost/assets/index.js:40:39894)
    at cbe (https://tauri.localhost/assets/index.js:40:39817)
