### ISSUE TITLE
Crash on lose on time

### ISSUE THREAD

**Issue by joaopinto24** [franciscoBSalgueiro/en-croissant#430]
### Describe the bug

An error occurred screen appears when losing on time, human or engine

### Reproduction

1. On Board tab, click play chess
2. Start a game with time settings set on time
3. Wait
4. Crash

### Platform and versions

Version: 0.11.1

Tauri version: 1.6.1

OS: Windows_NT x86_64 10.0.26100

### Stack trace

```Shell
Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Dl (https://tauri.localhost/assets/index.js:40:33914)
    at Yye (https://tauri.localhost/assets/index.js:38:24954)
    at Nw (https://tauri.localhost/assets/index.js:80:15863)
    at https://tauri.localhost/assets/index.js:80:15970
    at Array.forEach (<anonymous>)
    at https://tauri.localhost/assets/index.js:80:15959
    at Nw (https://tauri.localhost/assets/index.js:80:15863)
    at https://tauri.localhost/assets/index.js:80:15970
    at Array.forEach (<anonymous>)
    at https://tauri.localhost/assets/index.js:80:15959
```

**Comment by Dietr1ch** [comment]
I think I ran into a similar crash while about to lose on time  (Timer says 00:00.3) against local stockfish (installed by my package manager)



```text
Dl@tauri://localhost/assets/index.js:40:33919 Yye@tauri://localhost/assets/index.js:38:24956 Nw@tauri://localhost/assets/index.js:80:15864 forEach@[native code] @tauri://localhost/assets/index.js:80:15966 Nw@tauri://localhost/assets/index.js:80:15864 forEach@[native code] @tauri://localhost/assets/index.js:80:15966 Kh@tauri://localhost/assets/index.js:40:22383 ese@tauri://localhost/assets/index.js:40:27942 cl@tauri://localhost/assets/index.js:40:27600 ese@tauri://localhost/assets/index.js:40:30657 cl@tauri://localhost/assets/index.js:40:27600 ese@tauri://localhost/assets/index.js:40:27714 cl@tauri://localhost/assets/index.js:40:27600 ese@tauri://localhost/assets/index.js:40:27714 cl@tauri://localhost/assets/index.js:40:27600 ese@tauri://localhost/assets/index.js:40:27714 cl@tauri://localhost/assets/index.js:40:27600 ese@tauri://localhost/assets/index.js:40:27714 cl@tauri://localhost/assets/index.js:40:27600 ese@tauri://localhost/assets/index.js:40:27714 cl@tauri://localhost/assets/index.js:40:27600 ese@tauri://localhost/assets/index.js:40:27714 cl@tauri://localhost/assets/index.js:40:27600 ese@tauri://localhost/assets/index.js:40:27911 cl@tauri://localhost/assets/index.js:40:27600 ese@tauri://localhost/assets/index.js:40:27714 cl@tauri://localhost/assets/index.js:40:27600 ese@tauri://localhost/assets/index.js:40:30657 cl@tauri://localhost/assets/index.js:40:27600 ese@tauri://localhost/assets/index.js:40:27714 cl@tauri://localhost/assets/index.js:40:27600 ese@tauri://localhost/assets/index.js:40:27714 cl@tauri://localhost/assets/index.js:40:27600 ese@tauri://localhost/assets/index.js:40:27714 cl@tauri://localhost/assets/index.js:40:27600 ese@tauri://localhost/assets/index.js:40:27911 cl@tauri://localhost/assets/index.js:40:27600 ese@tauri://localhost/assets/index.js:40:27714 cl@tauri://localhost/assets/index.js:40:27600 ese@tauri://localhost/assets/index.js:40:27911 cl@tauri://localhost/assets/index.js:40:27600 ese@tauri://localhost/assets/index.js:40:27714 cl@tauri://localhost/assets/index.js:40:27600 ese@tauri://localhost/assets/index.js:40:27714 cl@tauri://localhost/assets/index.js:40:27600 ese@tauri://localhost/assets/index.js:40:27911 cl@tauri://localhost/assets/index.js:40:27600 ese@tauri://localhost/assets/index.js:40:27714 cl@tauri://localhost/assets/index.js:40:27600 ese@tauri://localhost/assets/index.js:40:27714 cl@tauri://localhost/assets/index.js:40:27600 ese@tauri://localhost/assets/index.js:40:27911 cl@tauri://localhost/assets/index.js:40:27600 ese@tauri://localhost/assets/index.js:40:27714 cl@tauri://localhost/assets/index.js:40:27600 ese@tauri://localhost/assets/index.js:40:27714 cl@tauri://localhost/assets/index.js:40:27600 ese@tauri://localhost/assets/index.js:40:27714 cl@tauri://localhost/assets/index.js:40:27600 ese@tauri://localhost/assets/index.js:40:29031 cl@tauri://localhost/assets/index.js:40:27600 ese@tauri://localhost/assets/index.js:40:27714 cl@tauri://localhost/assets/index.js:40:27600 ese@tauri://localhost/assets/index.js:40:27714 cl@tauri://localhost/assets/index.js:40:27600 ese@tauri://localhost/assets/index.js:40:27714 cl@tauri://localhost/assets/index.js:40:27600 ese@tauri://localhost/assets/index.js:40:27714 cl@tauri://localhost/assets/index.js:40:27600 ese@tauri://localhost/assets/index.js:40:27714 cl@tauri://localhost/assets/index.js:40:27600 ese@tauri://localhost/assets/index.js:40:30657 cl@tauri://localhost/assets/index.js:40:27600 ese@tauri://localhost/assets/index.js:40:27714 cl@tauri://localhost/assets/index.js:40:27600 ese@tauri://localhost/assets/index.js:40:27714 cl@tauri://localhost/assets/index.js:40:27600 ese@tauri://localhost/assets/index.js:40:30657 cl@tauri://localhost/assets/index.js:40:27600 ese@tauri://localhost/assets/index.js:40:27714 cl@tauri://localhost/assets/index.js:40:27600 ese@tauri://localhost/assets/index.js:40:27714 cl@tauri://localhost/assets/index.js:40:27600 ese@tauri://localhost/assets/index.js:40:27714 cl@tauri://localhost/assets/index.js:40:27600 ese@tauri://localhost/assets/index.js:40:27911 cl@tauri://localhost/assets/index.js:40:27600 ese@tauri://localhost/assets/index.js:40:27714 cl@tauri://localhost/assets/index.js:40:27600 ese@tauri://localhost/assets/index.js:40:27714 cl@tauri://localhost/assets/index.js:40:27600 ese@tauri://localhost/assets/index.js:40:27911 cl@tauri://localhost/assets/index.js:40:27600 ese@tauri://localhost/assets/index.js:40:27714 cl@tauri://localhost/assets/index.js:40:27600 ese@tauri://localhost/assets/index.js:40:27714 cl@tauri://localhost/assets/index.js:40:27600 ese@tauri://localhost/assets/index.js:40:27911
```
