### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Teals53** [franciscoBSalgueiro/en-croissant#455]
### Describe the bug

white loss in time and section is crashed

### Reproduction

stockfish vs stockfish no move time plus set time 10 second and lets them play

### Platform and versions

latest

### Stack trace

```Shell
Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Dl (https://tauri.localhost/assets/index.js:40:33914)
    at Yye (https://tauri.localhost/assets/index.js:38:24954)
    at Nw (https://tauri.localhost/assets/index.js:80:15863)
    at https://tauri.localhost/assets/index.js:80:15970
    at Array.forEach (<anonymous>)
    at https://tauri.localhost/assets/index.js:80:15959
    at Nw (https://tauri.localhost/assets/index.js:80:15863)
    at https://tauri.localhost/assets/index.js:80:15970
    at Array.forEach (<anonymous>)
    at https://tauri.localhost/assets/index.js:80:15959
```

**Comment by Teals53** [comment]
simply when the time runs out on any circumstances the game crashing no matter what
