### ISSUE TITLE
Randomly Chess Game Crashes

### ISSUE THREAD

**Issue by dreamers256** [franciscoBSalgueiro/en-croissant#465]
### Describe the bug

The game randomly crashed and I don't know why this happened, and that is what I got for error message.
the attached picture represents it.
![Screenshot 2024-12-13 225311](https://github.com/user-attachments/assets/20335af1-e073-47f1-84af-7a87fd9bc1a9)

### Reproduction

1. Play as white in en Croissant chess.
2. Against stockfish in time limited settings

### Platform and versions

Platform: Windows 11 Version 23H2( OS Build 22631.4541 )
Software the game was running: En Croissant ( Ver. 0.11.1)

### Stack trace

```Shell
Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Dl (https://tauri.localhost/assets/index.js:40:33914)
    at Yye (https://tauri.localhost/assets/index.js:38:24954)
    at Nw (https://tauri.localhost/assets/index.js:80:15863)
    at https://tauri.localhost/assets/index.js:80:15970
    at Array.forEach (<anonymous>)
    at https://tauri.localhost/assets/index.js:80:15959
    at Nw (https://tauri.localhost/assets/index.js:80:15863)
    at https://tauri.localhost/assets/index.js:80:15970
    at Array.forEach (<anonymous>)
    at https://tauri.localhost/assets/index.js:80:15959
```

**Comment by Teals53** [comment]
https://github.com/franciscoBSalgueiro/en-croissant/issues/455
