### ISSUE TITLE
Cannot have two MultiBanckends at the same time

### ISSUE THREAD

**Issue by Teals53** [franciscoBSalgueiro/en-croissant#472]
### Describe the bug

crash

### Reproduction

idk just appeared after closing one game

### Platform and versions

Cannot have two MultiBackends at the same time.
Error: Cannot have two MultiBackends at the same time.
    at hy.setup (https://tauri.localhost/assets/index.js:402:273)
    at PLt.handleRefCountChange (https://tauri.localhost/assets/index.js:403:5884)
    at Object.h [as dispatch] (https://tauri.localhost/assets/index.js:329:876835)
    at tjt.addTarget (https://tauri.localhost/assets/index.js:403:12325)
    at Mjt (https://tauri.localhost/assets/index.js:403:22489)
    at https://tauri.localhost/assets/index.js:403:31635
    at Sw (https://tauri.localhost/assets/index.js:40:24328)
    at NW (https://tauri.localhost/assets/index.js:40:31691)
    at tse (https://tauri.localhost/assets/index.js:40:31547)
    at obe (https://tauri.localhost/assets/index.js:40:31094)

**Comment by puddyglum** [comment]
Had the same issue.  Windows 11 Pro, AMD 5600x.  Restarting app resolved.  Neither the error nor the stack trace showed up in the log file.  I know I had been in the Settings area and then when I switched back to the Board, the Databases had a stack trace, and every window after that had the same stack trace.  I can't seem to recreate it, though.

**Comment by Redswap2** [comment]
> Had the same issue. Windows 11 Pro, AMD 5600x. Restarting app resolved. Neither the error nor the stack trace showed up in the log file. I know I had been in the Settings area and then when I switched back to the Board, the Databases had a stack trace, and every window after that had the same stack trace. I can't seem to recreate it, though.

Same on Windows 11, Intel CPU. This also happened when I returned from settings to my game (game was human vs human and I was in analysis mode).

**Comment by franciscoBSalgueiro** [comment]
fixed by https://github.com/franciscoBSalgueiro/en-croissant/commit/5b80adf04453ad1135e8b3c976cf4fac0b727e41
