### ISSUE TITLE
App crashes, when adding an closed Lichess Account

### ISSUE THREAD

**Issue by Nevsor** [franciscoBSalgueiro/en-croissant#83]
I tried adding my Lichess account although it has been closed to test, if en-croissant can still download its games.

The application immediately crashed and crashes every time I start it again. It only becomes usable again after deleting en-croissant's AppData directory.

I verified, that the same problem happens, if I try to add other closed accounts and that adding accounts, that are not closed, works.

# Steps to reproduce:
    1. Go to Accounts->Add Account
    2. Choose Website=Lichess and Username=Nevsor
    3. Click Add

# Additional information:
   OS: Windows 11
   en-croissant: v0.6.0

# Error message:

### Unexpected Application Error!

*Cannot read properties of undefined (reading 'ultraBullet')*
```
TypeError: Cannot read properties of undefined (reading 'ultraBullet')
    at https://tauri.localhost/assets/index.js:1123:126023
    at Array.map (<anonymous>)
    at NTt (https://tauri.localhost/assets/index.js:1123:125915)
    at nP (https://tauri.localhost/assets/index.js:38:19551)
    at Ok (https://tauri.localhost/assets/index.js:40:3143)
    at IJ (https://tauri.localhost/assets/index.js:40:44877)
    at AJ (https://tauri.localhost/assets/index.js:40:39819)
    at d5e (https://tauri.localhost/assets/index.js:40:39745)
    at S6 (https://tauri.localhost/assets/index.js:40:39596)
    at Dk (https://tauri.localhost/assets/index.js:40:35959)
```

**Comment by franciscoBSalgueiro** [comment]
Thanks, I didn't know that an account could have no ratings at all.
